In [ ]:
import numpy as np
np.__version__


'2.0.2'

In [ ]:
matrix = np.random.randint(1,6,size=(3,3))
matrix

array([[3, 3, 5],
       [1, 2, 2],
       [3, 3, 2]])

In [ ]:
det=np.linalg.det(matrix)
det

np.float64(-9.000000000000002)

In [ ]:
product = np.prod(matrix)
product

np.int64(3240)

In [ ]:
prod_1=np.prod(matrix[0])
prod_2=np.prod(matrix[1])
prod_3=np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(3240)

In [ ]:
sum = np.sum(matrix)
sum

np.int64(24)

In [ ]:
max_element=np.max(matrix)
print("Найбільший елемент матриці:", max_element)
min_element = np.min(matrix)
print("Найменший елемент матриці:", min_element)


Найбільший елемент матриці: 5
Найменший елемент матриці: 1


In [ ]:
mean=np.mean(matrix)
print("Середнє значення елементів матриці:",mean)

Середнє значення елементів матриці: 2.6666666666666665


In [ ]:
sqrt_matrix=np.sqrt(matrix)
print("Матриця квадратних коренів:")
print(sqrt_matrix)

Матриця квадратних коренів:
[[1.73205081 1.73205081 2.23606798]
 [1.         1.41421356 1.41421356]
 [1.73205081 1.73205081 1.41421356]]


In [ ]:
row_sums=np.sum(matrix,axis=1).reshape(-1,1)
print("Сума елементів кожного рядка:")
print(row_sums)

Сума елементів кожного рядка:
[[11]
 [ 5]
 [ 8]]


In [ ]:
vector=np.random.randint(0,10,size=25)
print("Початковий вектор:")
print(vector)

sorted_vector=np.sort(vector)[: : -1]

print("Вектор після сортування за спаданням:")
print(sorted_vector)

Початковий вектор:
[5 2 1 9 8 8 3 4 8 1 4 5 3 6 4 3 7 6 5 7 3 4 5 3 9]
Вектор після сортування за спаданням:
[9 9 8 8 8 7 7 6 6 5 5 5 5 4 4 4 4 3 3 3 3 3 2 1 1]


In [ ]:
from scipy import stats

mode = stats.mode(vector)
median = np.median(vector)
mean = np.mean(vector)
max_value=np.max(vector)
min_value=np.min(vector)
print("Мода:",mode)
print("Медіана:",median)
print("Середнє:",mean)
print("Максимальне значення:",max_value)
print("Мінімальне значення:",min_value)



Мода: ModeResult(mode=np.int64(3), count=np.int64(5))
Медіана: 5.0
Середнє: 4.92
Максимальне значення: 9
Мінімальне значення: 1


In [ ]:
matrix1 = np.random.randint(1,11, size=(4,4))
matrix2 = np.random.randint(1,11, size=(4,4))

print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)

Матриця 1:
[[9 2 7 6]
 [5 1 4 3]
 [7 3 8 5]
 [6 1 4 3]]

Матриця 2:
[[10  4  6  6]
 [ 8  7  9 10]
 [ 7  5  4  7]
 [ 7  9  8  6]]


In [ ]:
matrix_sum=matrix1+matrix2
matrix_diff=matrix1-matrix2
matrix_product = matrix1 * matrix2
matrix_division=np.divide(matrix1,matrix2, where=(matrix2!=0))

print("\nСума матриць:")
print(matrix_sum)
print("\nРізниця матриць:")
print(matrix_diff)
print("\nПоелементний добуток матриць:")
print(matrix_product)



Сума матриць:
[[19  6 13 12]
 [13  8 13 13]
 [14  8 12 12]
 [13 10 12  9]]

Різниця матриць:
[[-1 -2  1  0]
 [-3 -6 -5 -7]
 [ 0 -2  4 -2]
 [-1 -8 -4 -3]]

Поелементний добуток матриць:
[[90  8 42 36]
 [40  7 36 30]
 [49 15 32 35]
 [42  9 32 18]]


In [ ]:
x=np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
x1=x.reshape((3,3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
x2=np.arange(3.0)
x2

array([0., 1., 2.])

In [ ]:
np.multiply(x1,x2)


array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [ ]:
x1=np.arange(6)
x1

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.power(x1,3)

array([  0,   1,   8,  27,  64, 125])

In [ ]:
x2=np.array([1,2,3,3,4,1])
x1=np.arange(6)
x1 ** x2

array([  0,   1,   8,  27, 256,   5])

In [ ]:
vector=np.array([1,2,3,4,5])
vector

array([1, 2, 3, 4, 5])

In [ ]:
v1=np.matrix([1,2,3,4,5])
v1

matrix([[1, 2, 3, 4, 5]])

In [ ]:
v2=v1.T
v2

matrix([[1],
        [2],
        [3],
        [4],
        [5]])

In [ ]:
v=np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [ ]:
v[::-1]

array([5, 4, 3, 2, 1])

In [ ]:
v= np.flip(v)
v

array([5, 4, 3, 2, 1])

In [ ]:
print(np.mean(v))

3.0


In [ ]:
np.max(v)

np.int64(5)

In [ ]:
np.min(v)

np.int64(1)

In [ ]:
v1=np.array([1,2,3])
v2=np.array([4,5,6])

In [ ]:
v1

array([1, 2, 3])

In [ ]:
v2

array([4, 5, 6])

In [ ]:
np.dot(v1,v2)

np.int64(32)

In [ ]:
v=np.array([1,2,3,4,5])
norm=np.linalg.norm(v)
norm

np.float64(7.416198487095663)

In [ ]:
v/norm

array([0.13483997, 0.26967994, 0.40451992, 0.53935989, 0.67419986])

In [ ]:
v1=np.array([1,0,0])
v2=np.array([0,1,0])
np.dot(v1,v2)

np.int64(0)

In [ ]:
v=np.array([1,2,3,4,5,3])
np.unique(v)

array([1, 2, 3, 4, 5])

In [ ]:
vector=np.array([1,2,3,4,5])
length=np.linalg.norm(vector)
length

np.float64(7.416198487095663)

In [ ]:
np.isclose(length,5)
#не дорівнює

np.False_

In [ ]:
a=np.random.randint(0,11,(3,3))
a

array([[6, 8, 7],
       [0, 7, 0],
       [8, 3, 8]])

In [ ]:
np.linalg.det(a)

np.float64(-55.99999999999997)

In [ ]:
np.linalg.inv(a)

array([[-1.        ,  0.76785714,  0.875     ],
       [ 0.        ,  0.14285714,  0.        ],
       [ 1.        , -0.82142857, -0.75      ]])

In [ ]:
a=np.array([[1,3,-4],[0,2,-3],[-2,2,5]])
b=np.array([5,3,4])

x=np.linalg.solve(a,b)
print(x)

inv_a=np.linalg.inv(a)
x1=inv_a.dot(b)
print(x1)

[0.38888889 1.83333333 0.22222222]
[0.38888889 1.83333333 0.22222222]
